variables:
  IMAGE_NAME: whizus/poc/kcd-platform-prototype/kcd_demo_app
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA

stages:
  - build
  - containerize

build:
  stage: build
  image: node:20-alpine3.17
  script:
    - npm install

containerize:
  stage: containerize
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN
    - docker build -t $CI_REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
    - docker push $CI_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
